### ISSUE TITLE
History Size in MM 3.6 / min item count has no effect

### ISSUE THREAD

**Issue by mychaelo** [ESOUIMods/MasterMerchant#24]
After upgrading to MM 3.6 and importing all the data I've noticed that the History Size now has a hard cut off regardless of the min/max item count settings.

MM <3.6:
- If min item count is set, up to X items are retained in history even if these are older sales

MM 3.6:
- Only up to X days of sales are retained, so min item count doesn't have any effect now

I tested this on Bananas in Moon-Sugar Syrup, for which I had a couple sales recorded back in 2015 [|H1:item:57139:144:50:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h].

@Sharlikran 

Setting window screenshot:
![image](https://user-images.githubusercontent.com/2910415/132093634-79a84d6f-82ae-4a72-ace7-62f575f34606.png)

**Comment by Sharlikran** [comment]
Should be in the next version.

**Comment by mychaelo** [comment]
> 
> 
> Should be in the next version.

Yeah, 3.6.48 imported the MM history properly now, which took 2000 seconds instead of 9. I guess you should now also add the "not finished yet" to MM imports as well I guess 😄. Though I doubt there are many maniacs like me who still have sales back from ShopKeeper days:
![image](https://user-images.githubusercontent.com/2910415/132119793-4a512ea1-d19b-43b2-842d-f7a57dd548f0.png)
