### ISSUE TITLE
UI error while hovering item from blacklisted guild store

### ISSUE THREAD

**Issue by MysteryDragon** [ESOUIMods/MasterMerchant#26]
This bug introduced with today's version of MM, 3.6.46.
When I'm hovering any item from guild store of the guild which I blacklisted, it shows me the error about `operator < is not supported for number < nil` (MasterMerchant.lua:550; screenshot is attached).
![Screenshot_20210904_135710](https://user-images.githubusercontent.com/3968363/132094132-fc1348b4-01c6-4a85-a311-3584c5bd895d.png)

**Comment by MysteryDragon** [comment]
The reason of this error that in current code it's assumed that every guild store record will be in "bonanza" list, so after the list iteration in 542-549 lines you can think that `bonanzaSales` will never remains `nil`. But if there are no items in `bonanzaList` - which may be true if you're blacklisting some guild store - then `bonanzaSales` is still `nil`.

**Comment by MysteryDragon** [comment]
The fix I applied locally looks like that, 550-556 lines:
```
if bonanzaSales ~= nil and bonanzaSales >= 1 then
  bonanzaPrice = bonanzaPrice / bonanzaCount
end
--[[found an average price of 0.07 which X 200 is 14g
even 0.01 X 200 is 2g
]]--
if bonanzaPrice ~= nil and bonanzaPrice < 0.01 then bonanzaPrice = 0.01 end
```
Means there are additional check for the item being `nil`.

**Comment by Sharlikran** [comment]
I appreciate that. You could not be more correct. I did have a report of it in the comments section and I could not figure out why. After I read your explanation then it was a facepalm moment.

**Comment by Sharlikran** [comment]
I would assume it is working correctly now? @MysteryDragon

**Comment by MysteryDragon** [comment]
@Sharlikran yeah, looks fine, thank you!
