### ISSUE TITLE
Consider localising thousand and decimal separators

### ISSUE THREAD

**Issue by mychaelo** [ESOUIMods/MasterMerchant#28]
While translating MM to Russian I've noticed that there is no way to customize the number formatting. Well, there's SK_THOUSANDS_SEP from ye olde times that is not used anywhere, and that's about it. To my knowledge ZOS already have a handful of LUA functions to format numbers, so you could probably reuse those.

For example, how you would spell two millions forty two dollars and fifty six cents in different locales:
English and Japanese: $2,000,042.56
German: 2.000.042,56 $
French and Russian: 2 000 042,56 $

@Sharlikran

**Comment by Sharlikran** [comment]
Unfortunately I won't be doing this for now but I will keep it in mind. I did it once and it broke the deal filter. I have discussed it with sirinsidiator and he game me some possible solutions but not ETA on when I can implement that.
