### ISSUE TITLE
Extra junky symbols in MM price messages if no Bonanza data is available

### ISSUE THREAD

**Issue by mychaelo** [ESOUIMods/MasterMerchant#31]
If the item has no Bonanza data recorded for it, the resulting MM Price chat message will contain some junk near item's name:
```
MM price (913 sales/1187 items, 45 days): 178,787 :  for [Chromium Plating] 
```
Or more precisely, a space, a colon, and two more spaces between the price and itemLink.

While at it, you could also try to get rid of the extra space after itemLink if possible.

@Sharlikran

**Comment by Sharlikran** [comment]
I looked in all the places that manage that and it is using string.format() and GetString(), ChatEditControl:InsertText(), yet nothing has any extra junky spaces and such. The functions used are not MM specific functions.

**Comment by mychaelo** [comment]
@Sharlikran Fixed this locally with these changes:

https://github.com/mychaelo/MasterMerchant/commit/6fde5a6f5a00696719ab9785beca2b44d90f3ed2

**Comment by Sharlikran** [comment]
@mychaelo I will probably add that, just not gotten a round to it

**Comment by Sharlikran** [comment]
I didn't make all the changes but that should do, https://github.com/ESOUIMods/MasterMerchant/commit/f4ae1010bf20098f0e1e668d169d91f2d33a1129

**Comment by mychaelo** [comment]
> I didn't make all the changes but that should do, [f4ae101](https://github.com/ESOUIMods/MasterMerchant/commit/f4ae1010bf20098f0e1e668d169d91f2d33a1129)

That's all the changes that mattered anyway. Ty
