### ISSUE TITLE
Make more strings translatable

### ISSUE THREAD

**Issue by mychaelo** [ESOUIMods/MasterMerchant#32]
In Master Merchant:
- [x] Craft Cost (found in CraftCostPriceTip(), LinkHandler_OnLinkMouseUp(), myOnTooltipMouseUp(), myZO_InventorySlot_ShowContextMenu() functions)

In LibGuildStore:
- [x] Most of the addonmenu description texts
- [x] Majority of the chat messages sent during initialisation

@Sharlikran

**Comment by Sharlikran** [comment]
Those should be done now.
