### ISSUE TITLE
Russian Translation

### ISSUE THREAD

**Issue by mychaelo** [ESOUIMods/MasterMerchant#35]
This is a tracking issue / feedback thread for the Russian localisation of Master Merchant.

**Comment by mychaelo** [comment]
@Sharlikran Updated the RU files for 3.6.49 here:
https://github.com/mychaelo/MasterMerchant/commit/11779de458ddaa4cb8ef96006ccc3ea72dba1281

**Comment by Sharlikran** [comment]
@mychaelo okay there are some new strings for the latest release. When you have time can you take a look please? Use the master branch please.

**Comment by Sharlikran** [comment]
@mychaelo There are some new strings for the latest release. When you have time can you take a look please? Reference the master branch, and make the pull request on a new branch like you did before please.
