### ISSUE TITLE
Plugin UI crashed on game start ( operator .. is not supported for string .. nil)

### ISSUE THREAD

**Issue by Cjkjvfnby** [ESOUIMods/MasterMerchant#41]
Not being able to get the guild name should not be the reason for the addon crush.

The problem could be solved by changing the return value in the Data.lua
```diff
function internal:GetGuildNameByIndex(index)
-  if not index or not internal.guildNameByIdLookup[index] then return nil end
+  if not index or not internal.guildNameByIdLookup[index] then return "" end
  return internal.guildNameByIdLookup[index]
end
```

I'd also suggest to update `internal:GetAccountNameByIndex and internal:GetItemLinkByIndex(index)`

Full traceback:
```
user:/AddOns/MasterMerchant/MasterMerchant_UI.lua:979: operator .. is not supported for string .. nil
stack traceback:
user:/AddOns/MasterMerchant/MasterMerchant_UI.lua:979: in function 'MMScrollList:SetupReportsRow'
|caaaaaa<Locals> self = [table:1]{automaticallyColorRows = T}, control = ud, data = [table:2]{1 = 132617}, dataTable = [table:3]{}, actualItem = [table:4]{timestamp = 1665424804, guild = 81, quant = 5, price = 9000, itemLink = 742, seller = 109}, currentItemLink = "|H0:item:55553:337:50:0:0:0:0:...", currentSeller = "@Day_Night", actualItemIcon = "/esoui/art/icons/justice_stole...", fontString = "$(PROSE_ANTIQUE_FONT)|%d" </Locals>|r
user:/AddOns/MasterMerchant/MasterMerchant_UI.lua:1058: in function 'setupCallback'
|caaaaaa<Locals> control = ud, data = [table:2] </Locals>|r
/EsoUI/Libraries/ZO_Templates/ScrollTemplates.lua:2451: in function 'ZO_ScrollList_UpdateScroll'
|caaaaaa<Locals> self = ud, windowHeight = 570, activeControls = [table:5]{}, offset = 0, IS_REAL_NUMBER = F, activeIndex = 1, numActive = 0, allData = [table:6]{}, visibleDataIndices = [table:7]{1 = 1}, mode = 1, firstInViewVisibleIndex = 1, nextCandidateVisibleIndex = 12, currentDataIndex = 12, dataEntry = [table:8]{typeId = 1}, bottomEdge = 570, controlTop = 396, uniformControlHeight = 36, dataType = [table:9]{height = 36, selectable = T}, controlPool = [table:10]{m_NextFree = 13, m_NextControlId = 12}, control = ud </Locals>|r
/EsoUI/Libraries/ZO_Templates/ScrollTemplates.lua:2207: in function 'ZO_ScrollList_Commit'
|caaaaaa<Locals> self = ud, windowHeight = 570, selectionsEnabled = F, scrollableDistance = 78, foundSelected = F, i = 0 </Locals>|r
(tail call): ?
/EsoUI/Libraries/ZO_SortFilterList/ZO_SortFilterList.lua:154: in function 'ZO_SortFilterList:CommitScrollList'
|caaaaaa<Locals> self = [table:1], scrollData = [table:6] </Locals>|r
/EsoUI/Libraries/ZO_SortFilterList/ZO_SortFilterList.lua:137: in function 'ZO_SortFilterList:RefreshData'
|caaaaaa<Locals> self = [table:1] </Locals>|r
user:/AddOns/MasterMerchant/MasterMerchant_UI.lua:1063: in function 'MMScrollList:InitializeDataType'
|caaaaaa<Locals> self = [table:1], controlName = "MasterMerchantReportsWindow" </Locals>|r
user:/AddOns/MasterMerchant/MasterMerchant_UI.lua:1068: in function 'MMScrollList:New'
|caaaaaa<Locals> self = [table:11]{__isAbstractClass = F}, control = ud, skList = [table:1] </Locals>|r
user:/AddOns/MasterMerchant/MasterMerchant_UI.lua:3658: in function 'MasterMerchant:SetupScrollLists'
|caaaaaa<Locals> self = [table:12]{USE_TTC_AVERAGE = 2, purchasesViewSize = "purchases_vs", USE_MM_TTC_FORMAT = 3, USE_MM_AVERAGE = 3, USE_TTC_SUGGESTED = 1, AwesomeGuildStoreDetected = T, USE_CONDENSED_FORMAT = 2, guildSalesViewMode = "guild_vm", guildList = "Merchants of Magnus, The Noble...", reportsViewMode = "posted_vm", isInitialized = F, coinIcon = "|t16:16:EsoUI/Art/currency/cur...", reportsViewSize = "reports_vs", client_lang = "en", effective_lang = "en", salesViewMode = "self_vm", viewer = F, purchasesViewMode = "purchases_vm", supported_lang = T, reportsCanceledViewMode = "canceled_vm", reportsPostedViewMode = "posted_vm", customTimeframeText = "90 Days", itemsViewSize = "items_vs", name = "MasterMerchant", USE_BONANZA = 4, USE_DEFAULT_FORMAT = 1, listingsViewMode = "listings_vm", guildsViewSize = "guild_vs", oneYearInSeconds = 31104000, personalSalesViewMode = "self_vm", version = "3.7.25", isFirstScan = F, listingsViewSize = "listings_vs"} </Locals>|r
user:/AddOns/MasterMerchant/MasterMerchant.lua:4117: in function 'MasterMerchant:InitScrollLists'
|caaaaaa<Locals> self = [table:12] </Locals>|r
user:/AddOns/MasterMerchant/MasterMerchant.lua:4023: in function 'Queue'
user:/AddOns/MasterMerchant/Libs/LibExecutionQueue/LibExecutionQueue.lua:35: in function 'lib:Next'
|caaaaaa<Locals> self = [table:13]{Paused = F, Wait = 20}, nextFunc = [table:14]{2 = "InitScrollLists"} </Locals>|r
user:/AddOns/MasterMerchant/Libs/LibExecutionQueue/LibExecutionQueue.lua:36: in function 'func'
/EsoUI/Libraries/Globals/globalapi.lua:252: in function '(anonymous)'
```

**Comment by Sharlikran** [comment]
@Cjkjvfnby Sorry for the late reply, I don't read these much. I leave it that way for a reason.

It's an array of strings so I don't save the same account name hundreds or thousands of times.

Imagine an array like this

```
account names = {
[1] = "@Cjkjvfnby",
[2] = "@Sharlikran",
}
```

Now imagine 600,000 of them. 

```
account names = {
[45678] = "@Cjkjvfnby",
<snip>
[65476] = "@Sharlikran",
}
```

Now the file becomes corrupted because the game crashes. And you encounter those names again and they are added to the array.

```
account names = {
[1000] = "@Cjkjvfnby",
<snip>
[1015] = "@Sharlikran",
}
```

People keep trying to second guess this and just tell me to check for nil. It doesn't work that way. If you loose hundreds, thousands, or hundreds of thousands of account names because your game crashed there is no way to recover from that.

**Comment by Sharlikran** [comment]
![image](https://github.com/ESOUIMods/MasterMerchant/assets/1912426/b2133591-9f76-4c85-bb68-0159f782cc89)

For example I could do that. The file for the repeat strings to cut down on file size contains everything.

```
["accountNames"] = {
        ["@SomeUserName"] = 113621,
}
["itemLink"] = {
        ["|H0:item:69788:145:50:0:0:0:0:0:0:0:0:0:0:0:0:9:0:0:0:10000:0|h|h"] = 124710,
}
["guildNames"] = {
        ["@SomeGuildName"] = 100,
}
```

**Comment by Cjkjvfnby** [comment]
@Sharlikran, thank you for your response, 

The problem is that this information is used to build some UI elements and this causes the crash of the plugin.  

The case when save is corrupted is something you could not control, but making the plugin work is in your hands.  Probably you could move this nill protection to the place where strings are concatenated and this will fix that crash.

> If I was still storing the item links for each sale and you had 650,000 sales times 65 bytes (it's a bit more) for the item Link, then that's 6,500,000,000 bytes. (6.5B bytes)

That a big number writing/reading this to/from the disc is quite expensive.

If you ever decide to spend some time on the performance of this data structure and will need a second opinion on that, feel free to reach me.  I have some experience with data structures/databases/inventing binary formats to store the data.

**Comment by Sharlikran** [comment]
Maybe I provided too much information, because it doesn't seem like you understood.

["string key"] = integer,

Once the string is gone you have no way to recover that. It's an arbitrary number. number = number + 1. So every account name is assigned an integer. Once the data is corrupted and the strings are gone what once was Cjkjvfnby = 1000, could be Cjkjvfnby  = 1. And 1000 could belong to AwesomePlayer. So your personal sale from a month ago would belong to AwesomePlayer and not show up in your personal sales anymore and you would ask me why.

> If you ever decide to spend some time on the performance of this data structure and will need a second opinion on that, feel free to reach me. I have some experience with data structures/databases/inventing binary formats to store the data.

What would be your simplest suggesting. You can not read and write from the disc using anything but the ZOS provided functionality. You can not specify a file name or a folder. Many people want this in CSV or Json or whatever. You can't do that. You output to these files in the ZOS provided format. What are you going to do use base 62? Then convert it from base 62 to Lua?

Before you suggest anything I'm trying to be respectful but you can't do anything ZOS doesn't want. This format has been this way for 5 or more years. There are 16 data files because of table size and line number restrictions. Are you gonna write the Lua equivalent of lzh or something?

I don't see how you can do it differently when ZOS would not allow it.

**Comment by Sharlikran** [comment]
```Lua
  [1] = 
  {
      ["price"] = 25000,
      ["quant"] = 1,
      ["timestamp"] = 1655688466,
      ["wasKiosk"] = false,
      ["guild"] = 2,
      ["id"] = "1873582931",
      ["itemLink"] = 5359,
      ["buyer"] = 5509,
      ["seller"] = 21471,
  },
```
That is a current sale.

**Comment by Sharlikran** [comment]
@sirinsidiator I'm not sure I want to have the discussion with Cjkjvfnby, because I'm not really aware of a better way. Aside from using integers as a key rather then a string like you mentioned today. Howver, I don't know as much as you Siri and while I'm reluctant to go down the path of ZOS doesn't allow us to do that with saved variables, I'd rather try to learn something new if I can.

**Comment by Sharlikran** [comment]
> The case when save is corrupted is something you could not control, but making the plugin work is in your hands. Probably you could move this nill protection to the place where strings are concatenated and this will fix that crash.

Siri he understands I can't control whether or not the game crashes. But he didn't get what I meant when I explained that once the account names, guild names, and item links, are gone you can't recover form that. So I can't seem to tell him the nil protection is useless. 

When those tables for the strings get reset to an emtpy table. It's like a FedEx person came to a house to deliver a package and there was a gas leak that caused the house to explode. There hose is gone.

**Comment by Sharlikran** [comment]
@otac0n if you have anything to add after Cjkjvfnby makes a suggesting and want to chime in feel free.

**Comment by Sharlikran** [comment]
@Cjkjvfnby if you were not aware, the saved variables are only saved when a player logs out or reloads the UI.

**Comment by Sharlikran** [comment]
If you need mroe visuals this is why the error happens.

### Not the arrays are empty.
```
["accountNames"] = {
}
["itemLink"] = {
}
["guildNames"] = {
}
```

### Sale in the MM database

```Lua
  [1] = 
  {
      ["price"] = 25000,
      ["quant"] = 1,
      ["timestamp"] = 1655688466,
      ["wasKiosk"] = false,
      ["guild"] = 2,
      ["id"] = "1873582931",
      ["itemLink"] = 5359,
      ["buyer"] = 5509,
      ["seller"] = 21471,
  },
```
The function sees that it need to fine buyer 5509, yet there is none.

**Comment by Cjkjvfnby** [comment]
> Maybe I provided too much information because it doesn't seem like you understood about the arrays for the guild names, the account names, and the item links.

In the database world, this thing is called normalization.  Besides other bonuses, it helps to save space when you need to store relations.  


> What are you going to do use base 62? Then convert it from base 62 to Lua? Are you gonna write the Lua equivalent of lzh or something?

Does API allow to saving of binary variables?  It looks like not.  And conversion binary to text will probably eat all benefits.

> I'd rather be respectful and see what you have to say. 
Thank you.  I am not suggesting any Java or JSON, this just won't work. Also, I don't sure that a huge improvement is possible. 


> I'm just skeptical because you can't do anything ZOS doesn't want.

I am pretty sure that this plugin is not what they want, but it exists.  People always find ways, and you are already a part of this.

> I do not wish to make it this

What is the reason?  Do you open variable files manually?  

It won't affect code readability if you add a couple of variables instead of names.
```diff
- itemLink = saleData["itemLink"]
+ local itemLink = "i"
+ itemLink = saleData[itemLink]
```

> ["itemIcon"] = "/esoui/art/icons/crafting_planfurniture_woodworking_3.dds",

I haven't launched a game for a while, so my source of data might be a bit outdated.

This looks like a subject for normalization.  `["itemIcon"] = <number>` will eat less space. Same for the `itemAdderText` and `itemDesc`.

These things are not hard to do and fit the current architecture, but the gain is also a couple of percents. :( 


Sorry for the newb questions, what is the limit of the variable file?  Is it a number of keys on the map? Or memory per addon? Or just the size of the saved file?

When the game crashes will it ruin all files, or only some that were changed and the saving process is in progress?
