### ISSUE TITLE
ui error on joining new guild

### ISSUE THREAD

**Issue by user99** [ESOUIMods/MasterMerchant#43]
Master Merchant updated to latest production version as are required Libs. Attached output as txt file
[userAddOnsMasterMerchantLibsLibGuil.txt](https://github.com/ESOUIMods/MasterMerchant/files/11034220/userAddOnsMasterMerchantLibsLibGuil.txt)

user:/AddOns/MasterMerchant/Libs/LibGuildStore/Data.lua:362: operator * is not supported for number * nil
stack traceback:
user:/AddOns/MasterMerchant/Libs/LibGuildStore/Data.lua:362: in function 'internal:QueueGuildHistoryListener'
|caaaaaa<Locals> self = [table:1]{totalListings = 674, GS_NA_NAMESPACE = "datana", cancelledNamespace = "cancelleditemsna", dataNamespace = "datana", GS_NA_PRICING_NAMESPACE = "pricingdatana", GS_NA_VISIT_TRADERS_NAMESPACE = "visitedNATraders", GS_CHECK_GUILDNAME = "guildNames", PlayerSpecialText = "hfdkkdfunlajjamdhsiwsuwj", GUILD_MEMBER_PURCHASE = 1, pir_index_count = 35, GS_EU_NAME_FILTER_NAMESPACE = "namefiltereu", GS_NA_FIRST_RUN_NAMESPACE = "firstRunNa", totalPurchases = 46, GS_NA_PURCHASE_NAMESPACE = "purchasena", GS_EU_POSTED_NAMESPACE = "posteditemseu", GS_EU_GUILD_LIST_NAMESPACE = "currentEUGuilds", GS_ALL_PRICING_NAMESPACE = "pricingdataall", GS_CHECK_ITEMLINK = "itemLink", GS_EU_VISIT_TRADERS_NAMESPACE = "visitedEUTraders", isDatabaseBusy = F, guildListNamespace = "currentNAGuilds", accountNamesCount = 6752, NON_GUILD_MEMBER_PURCHASE = 0, GS_EU_LIBHISTOIRE_NAMESPACE = "libhistoireeu", viewer = F, GS_EU_PRICING_NAMESPACE = "pricingdataeu", GS_EU_NAMESPACE = "dataeu", purchasesNamespace = "purchasena", verboseLevel = 4, listingsToReset = "", GS_NA_GUILD_LIST_NAMESPACE = "currentNAGuilds", GS_NA_CANCELLED_NAMESPACE = "cancelleditemsna", GS_EU_LISTING_NAMESPACE = "listingseu", GS_CHECK_ACCOUNTNAME = "accountNames", nameFilterNamespace = "namefilterna", pricingNamespace = "pricingdatana", sr_index_count = 9, pr_index_count = 0, firstrunNamespace = "firstRunNa", itemLinksCount = 20042, GS_EU_PURCHASE_NAMESPACE = "purchaseeu", postedNamespace = "posteditemsna", GS_NA_NAME_FILTER_NAMESPACE = "namefilterna", GS_NA_LIBHISTOIRE_NAMESPACE = "libhistoirena", libHistoireNamespace = "libhistoirena", GS_NA_POSTED_NAMESPACE = "posteditemsna", totalCanceled = 21, GS_EU_CANCELLED_NAMESPACE = "cancelleditemseu", totalSales = 4918, client_lang = "en"}, guildId = 822621 </Locals>|r
user:/AddOns/MasterMerchant/MasterMerchant_UI.lua:3955: in function 'OnPlayerJoinedGuild'
|caaaaaa<Locals> eventCode = 327703, guildId = 822621, guildName = "Definitely A Cult" </Locals>|r

**Comment by Sharlikran** [comment]
I believe this was resolved in https://github.com/ESOUIMods/MasterMerchant/commit/d18a81115fa4970f44b70fd67873265981819a59
