### ISSUE TITLE
MM folder attached

### ISSUE THREAD

**Issue by ghostbane38** [ESOUIMods/MasterMerchant#7]
[MasterMerchant.zip](https://github.com/ESOUIMods/MasterMerchant/files/5284052/MasterMerchant.zip)

**Comment by Sharlikran** [comment]
I was asking for the Addons folder not the Github folder. Because I simply do not see any columns.

**Comment by Sharlikran** [comment]
@ghostbane38 please drop a zip of your MasterMerchant folder directly from your addons folder. Because so far I have to versions already. Yoir zip from your comment and the repo.

**Comment by ghostbane38** [comment]
@Sharlikran The zip I attached is the one that is in my Addons folder.

It is an upgraded copy with the bulk data method I discussed the other day.

If I take the copy from the PR, and put it in my Addons folder, this also works in-game.

**Comment by ghostbane38** [comment]
@Sharlikran Could you perhaps try the zip without the SavedVars I sent? To see if you get that error again? Because the screenshot you posted in glitter seems to be a data related error, rather than a core MM one.

**Comment by Sharlikran** [comment]
I didn't use your MasterMerchant.lua file from the saved vars folder.

**Comment by Sharlikran** [comment]
![image](https://user-images.githubusercontent.com/1912426/94329294-9cc71680-ff6e-11ea-9220-cb6125698f9b.png)

It has to be working to some extent or I would not have the drop down menu. Although it is in a really odd place.

**Comment by Sharlikran** [comment]
[AddOns.zip](https://github.com/ESOUIMods/MasterMerchant/files/5286136/AddOns.zip)

Rename your Addons folder to something like `AddOns_cur` and then use the Addons folder from the zip in place of your old one.

**Comment by ghostbane38** [comment]
@Sharlikran So I followed your instructions and have received no LUA errors.

Although, the Columns do not display on initial load, despite in the settings it says "Display Info on Guild Roster: On". If I toggle this Off, and then On again, and open the Guild Roster, the columns appear.

On doing a bit of debugging, it appears that in the LAM manifest I was setting `MasterMerchant.systemSavedVariables.diplayGuildInfo` and not `self:ActiveSettings().diplayGuildInfo`.

As I was using character specific settings, and you are using account wide settings, this is where our issue happened.

So, changing these 2 lines in the LAM callbacks will fix the rendering issue.

Again, I have not received your LUA error on any scenario of using your SavedVars, I have done both of the following,

1. Replacing my MM SV LUA with your MM SV LUA in my SavedVariables folder
2. Removing everything in my SavedVariables folder, and just having your MM SV LUA

I will re-attach a new MM copy with the Settings change.

**Comment by ghostbane38** [comment]
Wait a moment, my original version was using `self:ActiveSettings().diplayGuildInfo`, the `MasterMerchant.systemSavedVariables.diplayGuildInfo` was one of your changes?

Even with your `MasterMerchant.systemSavedVariables.diplayGuildInfo`, toggling the setting Off, On, it will render the roster. It won't on initial load because it is determining from ActiveSettings() and not the systemSavedVariables.

**Comment by Sharlikran** [comment]
> Wait a moment, my original version was using self:ActiveSettings().diplayGuildInfo

I am aware of the `self:ActiveSettings().diplayGuildInfo` settings and will be doing away with that.

>was one of your changes?

Yes because with the original pull request as is or with my changes I do not see the columns. Regardless of how many times I toggle the setting on or off in the LAM menu and regardless of how many times I reload my UI.

![image](https://user-images.githubusercontent.com/1912426/94341094-a034bf00-ffbb-11ea-9d34-5a1080fd70e7.png)

I don't see a way to troubleshoot the columns or the anchors and provide XY offsets but as shown in my screen shot the dropdown to choose "This Week" or "Last Week" is in the upper left corner.

![image](https://user-images.githubusercontent.com/1912426/94341205-6c0dce00-ffbc-11ea-8e72-e5f1e97f9124.png)

**Comment by ghostbane38** [comment]
@Sharlikran Would you be able to send me a screenshot of,

`/tbug ZO_GuildRosterHeadersMM_Sold` ?
